spring:
  profiles:
    active:
    - dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
# 邮箱服务器地址
    host: smtp.qiyi.163.com
# 用户名
    username: xxx@oo.com
# 密码 
    password: xxyyooo
    default-encoding: UTF-8
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
            required: true
# 自定义变量
mail:
  fromMail:
# 以谁来发送邮件
    addr: xxx@oo.com