debug: false
#配置服务器参数
server:
  port: 8000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 
  redis:
# Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    pool:
# 连接池最大连接数（使用负值表示没有限制）
      max-active: 20
# 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
# 连接池中的最大空闲连接
      max-idle: 8
      min-idle: 0
# 连接超时时间（毫秒
    timeout: 0
#配置日志参数
logging:
  file: Log.log
  level:
    root: info
